# Automatically updated by the winget bot at 2021/Jun/18
PackageIdentifier: WhatsApp.WhatsApp
PackageVersion: 2.2123.7
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://web.whatsapp.com/desktop/windows/release/x64/WhatsAppSetup.exe
  InstallerSha256: 000480A83F922EC02B811A101F1C4D7E38FB27A328E8B044C1D9455BBCF651F5
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://web.whatsapp.com/desktop/windows/release/ia32/WhatsAppSetup.exe
  InstallerSha256: CF8B3295FDC0D22C11EFCDF07D9483558FF7C47F9D60CCA57D4484D07E01BDBD
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
