# Created using YamlCreate.ps1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Stardock.Start10
PackageVersion: 1.96
MinimumOSVersion: 10.0.0.0
Platform:
- Windows.Desktop
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: exe
  Scope: machine
  InstallerUrl: https://cdn.stardock.us/downloads/public/software/start/Start10_setup.exe
  InstallerSha256: 48A3A64CD2D81A608795D1109B2F2C701E51D58BDD1A8F7D82BA4C1870604723
  InstallerSwitches:
    Silent: /s
    SilentWithProgress: /s
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
