# Automatically updated by the winget bot at 2021/Jun/17
PackageIdentifier: LogMeIn.LastPass
PackageVersion: 4.74.0.2142
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x86
  InstallerType: msi
  InstallerUrl: https://download.cloud.lastpass.com/windows_installer/LastPassInstaller.msi
  InstallerSha256: C0BD7AB3BDD0727EC328163C25A6A0909D0F55DF604F724A053DC1E7FF280676
  ProductCode: "{B987099D-6575-4F1D-A402-630FAD9F8984}"
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
