# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: TeamSonarr.Sonarr
PackageVersion: 3.0
Installers:
- Architecture: x64
  InstallerUrl: https://download.sonarr.tv/v3/main/3.0.6.1196/Sonarr.main.3.0.6.1196.windows.exe
  InstallerType: inno
  InstallerSha256: DE416C10271A441AC971E4E612585607CE89F8AEDA35A814661D5B78C0C5E3C8
ManifestType: installer
ManifestVersion: 1.0.0

