# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: KDE.KDEConnect
PackageVersion: 21.04.2.626
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/626/artifact/kdeconnect-kde-21.04.2-626-windows-msvc2019_64-cl.exe
  InstallerSha256: AB1DC3FC4B34CD7527C59956109B61B905AD00228231552E71548B680BE89E58
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
ManifestType: installer
ManifestVersion: 1.0.0

