# Automatically updated by the winget bot at 2021/Jun/17
PackageIdentifier: Huawei.Welink
PackageName: Welink
PackageVersion: 7.6.1
Publisher: Huawei
License: copyright (c) Huawei
LicenseUrl: https://www.huaweicloud.com/declaration/statement.html#
PackageUrl: https://www.huaweicloud.com/product/welink-download.html
ShortDescription: A unified communication and collaboration platform that combines persistent workplace chat and video meetings.
Tags:
- huawei
- meeting
- video
- work
- cloud
- collaboration
- electron
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://welink.huaweicloud.com/download/WeLink_setup.exe
  InstallerSha256: A1BBA32B9D55D0F6581556582C6A2C2EFE662C252481A8FD4EF6E94DF752D506
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
