# Created using wingetcreate

PackageIdentifier: Badlion.BadlionClient
PackageVersion: 3.2.0
PackageLocale: en-US
Publisher: Badlion
PackageName: Badlion Client
License: © 2013-2021 ESL Gaming Online, Inc.
# LicenseUrl: https://www.badlion.net/tos
# PrivacyUrl: https://www.badlion.net/privacy
ShortDescription: Badlion Client is a Minecraft launcher with lots of features.
ManifestType: defaultLocale
ManifestVersion: 1.0.0
