# Automatically updated by the winget bot at 2021/Jun/19
PackageIdentifier: ActiveState.ActivePerl
Publisher: ActiveState
PackageName: ActivePerl
PackageVersion: 5.28.1001
Moniker: perl
License: © 2020 ActiveState Software Inc. All rights reserved.
LicenseUrl: https://www.activestate.com/wp-content/uploads/2018/10/activestate_community_edition_software_license_agreement.pdf
InstallerType: msi
Tags:
- perl
ShortDescription: Support your mission-critical applications with commercial-grade Perl from ActiveState – The world's most trusted Perl distribution.
PackageUrl: https://www.activestate.com/products/perl/
Installers:
- Architecture: x64
  InstallerUrl: https://cli-msi.s3.amazonaws.com/ActivePerl-5.28.msi
  InstallerSha256: 055C83BC782EF7CEA5E9406FC670B25A1AF2F24614A863080FBDA36DD5F2FF80
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
