# Created using wingetcreate

PackageIdentifier: IObit.AdvancedSystemCare
PackageVersion: 14.4.0.275
PackageLocale: en-US
Publisher: IObit
PackageName: Advanced SystemCare
License: © IObit. All rights reserved.
ShortDescription: Advanced SystemCare can make a personalized plan for you to scan and clear tons of junk files, unnecessary logs, and caches, leftovers from the third-party tools.
ManifestType: defaultLocale
ManifestVersion: 1.0.0
