# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: BraveSoftware.BraveBrowser-Nightly
PackageVersion: 91.1.28.13
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Protocols:
- http
- https
FileExtensions:
- html
- htm
- url
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.28.13/BraveBrowserStandaloneSilentNightlySetup.exe
  InstallerSha256: 8BD6B08963E2571AF2EF717C93FD730D169E406D75D0C76D05B21CE58276CCDA
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://github.com/brave/brave-browser/releases/download/v1.28.13/BraveBrowserStandaloneSilentNightlySetup32.exe
  InstallerSha256: 6A24F7947F0711E4A5BE4DDF38E3558F10D9687902621344C9DD3D70FF35FE47
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0

