# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: UbiquitiInc.WiFimanDesktop
PackageVersion: 1.1.0
PackageLocale: en-US
Publisher: Ubiquiti Inc.
PackageName: WiFiman Desktop
License: Proprietary
Copyright: Copyright © 2023 Ubiquiti Inc.
ShortDescription: WiFiman is a desktop app which can scan local network for active devices and configure them.
ReleaseNotesUrl: https://community.ui.com/releases/WiFiman-Desktop-1-1-0/f30311b3-a0d4-4661-97f0-ca7f4c9a10c5
ManifestType: defaultLocale
ManifestVersion: 1.6.0
