# Automatically updated by the winget bot at 2021/Jun/17
PackageIdentifier: Google.ChromeBeta
PackageVersion: 68.104.49211
MinimumOSVersion: 10.0.0.0
FileExtensions:
- html
- htm
- url
Protocols:
- http
- https
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise64.msi
  InstallerSha256: 6E4C83579CCC6910D804587EAEB8805010BB275826E27A3408FBBD280C22BCC6
  ProductCode: "{EB7F364E-E568-3C3F-8B2D-4434F6C3DF5D}"
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
- Architecture: x86
  InstallerType: msi
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise.msi
  InstallerSha256: DC02A56D5C272D541C23F30CD400DB49837159203F35AE3087111069CF5C55BC
  ProductCode: "{00566E2B-6B8D-3469-9080-804F4976ECCF}"
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
