# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: vim.vim
PackageVersion: 8.2.3033
Installers:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/vim/vim-win32-installer/releases/download/v8.2.3033/gvim_8.2.3033_x64.exe
  InstallerSha256: A317850D082065D9CB3D3F90DD864D9429700383D146804D899B88CF193E2E87
- Architecture: x86
  InstallerType: nullsoft
  InstallerUrl: https://github.com/vim/vim-win32-installer/releases/download/v8.2.3033/gvim_8.2.3033_x86.exe
  InstallerSha256: E094AB6A2DC46D3625D2EB561668F5F513DFFAC2F6742D82F5F7297B06D84247
ManifestType: installer
ManifestVersion: 1.0.0

