# Automatically updated by the winget bot at 2021/Jun/20
PackageIdentifier: Project64.Project64
PackageVersion: 3.0.1.5664
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://www.pj64-emu.com/file/setup-project64-3-0-0-5632-f83bee9/
  InstallerSha256: D3F8069295EA8B9DB9F4129B138969A070E3CB4DA17DF0A5F54A8E08DF3C4723
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
