# Created using wingetcreate

PackageIdentifier: Flash-Integro.VSDCFreeVideoEditor
PackageVersion: 6.7.4.300
Installers:
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://downloads.videosoftdev.com/video_tools/video_editor_x64.exe
  InstallerSha256: 90A5DFEF70878098B675DDA1DD8FB08AC8E19A75D3589D29E654172DDC1261A3
ManifestType: installer
ManifestVersion: 1.0.0
