# Created using wingetcreate

PackageIdentifier: Flash-Integro.VSDCFreeVideoEditor
PackageVersion: 6.7.4.300
PackageLocale: en-US
Publisher: Flash-Integro LLC
PackageName: VSDC Free Video Editor
License: Copyright (c) 2020 Flash-Integro LLC
ShortDescription: This free multimedia suite brings a set of tools for editing video, improving audio, recording voice overs, capturing desktop screen, and more.
ManifestType: defaultLocale
ManifestVersion: 1.0.0
